### ISSUE TITLE
Unit of delay in requeue

### ISSUE THREAD

**Issue by xavierchow** [dudleycarr/nsqjs#101]
> requeue(delay=null, backoff=true) The delay is in seconds. This is how long nsqd will hold on the message before attempting it again. The backoff parameter indicates that we should treat this as an error within this process and we need to backoff to recover.

I believe the delay should be milliseconds, I verified with the following script with a single reader:
```js
const nsq = require('nsqjs');

const reader = new nsq.Reader('sample_topic', 'test_channel', {
  lookupdHTTPAddresses: '127.0.0.1:4161'
});

reader.connect();
let counter = 0;
let start;
reader.on('message', function (msg) {
  counter++;
  console.log('Received message [%s]: %s', msg.id, msg.body.toString());
  if (counter === 1) {
    start = Date.now()
    msg.requeue(2000, false);
  }
  if (counter === 2) {
    console.log('elapsed in %d milliseconds', Date.now() - start);
    msg.finish();
  }
});
```
The output is `elapsed in 2013 milliseconds`.

**Comment by cwhitten** [comment]
+1 we've seen the same thing. Fixing the documentation should clear it up!

**Comment by xavierchow** [comment]
Doc updated, closing.
