### ISSUE TITLE
Do I need both nsqd and nslookupd daemons running on the Reader?

### ISSUE THREAD

**Issue by thelinuxlich** [dudleycarr/nsqjs#104]
Because even if I set the nsqdTCPAddresses  to an empty array, it's throwing "Caught exception: Error: connect ECONNREFUSED 127.0.0.1:4150" constantly

**Comment by dudleycarr** [comment]
You don't need to run both `nsqd` and `nslookupd` for a functional `Reader`. You should be able to run just `nsqd` and have the `Reader` connect to it by specifying `nsqdTCPAddresses`. Would you mind sharing the code snippet for me to see how you're using the `Reader`?

**Comment by thelinuxlich** [comment]
```javascript
reader = new nsq.Reader("batch", "default", {
        maxInFlight: 100,
        lookupdHTTPAddresses: '127.0.0.1:4161'
});
```

Oh, and by the way I was getting crazy because I was losing half the messages, but restarting the nsqd  instances + Writer services solved the issue. Have you ever seen something like this? The Writer nsqds are pointing to the Reader nsqlookupd instances

**Comment by dudleycarr** [comment]
The configuration above will definitely use the `lookupd` instances -- I thought previously that you didn't want to use `lookupd`? 

I'm not sure what you mean by "Writer nsqds" vs "Reader nsqlookupd" instances. I would highly recommend simplifying your topology to a single `nsqd` instance and have the Reader connect directly to it instead of `lookupd`. 

`nsqadmin` is also your friend here in terms of debugging what's happening with messages. If I had to guess, you're losing messages because they're timing out and being discarded after too many retries. `nsqadmin` would help you see that my looking at the `timedout` values for a particular channel.

**Comment by thelinuxlich** [comment]
Oh no, I just want to understand the nsqlookupd role. I have a job queue, where microservices spawn a Writer to send jobs to Reader microservices. Each Writer has a nsqd systemd service like this:

```
/usr/local/bin/nsqd -lookupd-tcp-address=192.168.0.10:4160 -lookupd-tcp-address=192.168.0.11:4160
```
Pointing to nsqlookupd addresses, which are the consumers

**Comment by thelinuxlich** [comment]
I guess I'm using it wrong, please check it out:

Writer(Producer) side:

```javascript
w = new nsq.Writer('127.0.0.1', 4150)
```

I thought that I should point to the local nsqd instance and when I send a message, it would "spread" to the nsqlookupd consumer addresses but that's not how it works, right? The Writer should point to the nsqd consumer address(or addresses, but it doesn't support an array of hosts) and probably the Writer doesn't even need to have a nsqd instance running.

**Comment by thelinuxlich** [comment]
I'm confused, because looking at the tests of this lib, it seems that the producer would connect to a nsqlookupd array of hosts, and have a round-robin delivery of messages to consumers

**Comment by dudleycarr** [comment]
Having a local `nsqd` is over optimizing, IMO. `nsqd`s can handle a large volume of messages. Also, using `localhost` for names could cause some discovery issues. I would suggest starting out with a single `nsqd` and a single `nsqlookupd` across each of your hosts and using the IP of that host for all of the configuration.

If you'd like to understand the role of the `nsqlookupd`s, I would take a look at this slide:
https://speakerdeck.com/snakes/nsq-nyc-golang-meetup?slide=60

**Comment by thelinuxlich** [comment]
So the Producer points to a remote nsqd address(Consumer), there is no way to do a round-robin delivery of messages?

**Comment by dudleycarr** [comment]
The support for connecting to multiple `nsqlookupd`s is definitely there and we use it regularly. I'm going to close this issue since I believe there isn't a bug here in the library, but rather a configuration issue.

**Comment by dudleycarr** [comment]
Messages are automatically distributed to all `Reader`s on a channel. It's not purely round robin, but definitely that all participate in the processing of the messages on a given channel.

**Comment by thelinuxlich** [comment]
Ok, so this:

```
w = new nsq.Writer('192.168.0.10', 4150)
```

Where 192.168.0.10 is a remote nsqd node, if it goes down, the Writer won't have knowledge of other alive nsqd nodes and it will go down too, am I right?

**Comment by dudleycarr** [comment]
Writers, unlike Readers, don't connect to multiple `nsqd` instances. If you wanted to have your publisher aware of multiple `nsqd`s then that would be something you would have to do.

**Comment by thelinuxlich** [comment]
But that isn't solved by connecting the Writer to a local nsqd instance which points to an array of nsqlookupd hosts, which will distribute the messages to consumers subscribing to the topic/channel?

**Comment by thelinuxlich** [comment]
Quoting from the docs:

```
nsqlookupd is a daemon that records and disseminates the state of an NSQ cluster at runtime. nsqd instances maintain persistent TCP connections to nsqlookupd and push state changes across the wire. Specifically, an nsqd registers itself as a producer for a given topic as well as all channels it knows about. This allows consumers to query an nsqlookupd to determine who the producers are for a topic of interest, rather than hard-coding that configuration. Over time, they will learn about the existence of new producers and be able to route around failures.

The only changes you need to make are to point your existing nsqd and consumer instances at nsqlookupd (everyone explicitly knows where nsqlookupd instances are but consumers don’t explicitly know where producers are, and vice versa).
```

**Comment by thelinuxlich** [comment]
This Segment article seems to recommend that the publisher connects to a local nsqd instance, which in turn advertises itself to nsqlookupd hosts, thus distributing the messages

https://segment.com/blog/scaling-nsq/
