### ISSUE TITLE
nsqdTCPAddresses should be optional if the Reader has valid lookupdHTTPAddresses 

### ISSUE THREAD

**Issue by thelinuxlich** [dudleycarr/nsqjs#105]
Talking to @mreiferson on NSQ freenode channel about this, the consumer(reader) side doesn't need to connect directly to a nsqd host if it can poll nsqlookupd hosts for nsqd nodes. But if I specify an empty nsqdTCPAddresses array it wll keep throwing an exception complaining about nsqd hosts.

**Comment by joshgummersall** [comment]
This should already be the case. If you specify a set of nsqlookupd addresses the reader will query them for any nsqd nodes to connect to. [See here](https://github.com/dudleycarr/nsqjs/blob/master/src/reader.coffee#L73)

**Comment by thelinuxlich** [comment]
yeah, but it will throw exceptions ocasionally

**Comment by joshgummersall** [comment]
Can you include a stack trace? The exception is almost certainly not related to a reader connecting (provided your configuration is correct).

Running the following:
```bash
$ nsqlookupd
```

And then running this:
```js
var Reader = require('nsqjs').Reader;

var reader = new Reader('sample_topic', 'default', {
    lookupdHTTPAddresses: ['localhost:4161']
});

reader.connect();
reader.on('message', function (msg) {
    console.log(msg.json());
    msg.finish();
});
```

produces zero exception, which is expected.
