### ISSUE TITLE
Reader listen before writer publish

### ISSUE THREAD

**Issue by xavierchow** [dudleycarr/nsqjs#106]
It seems that the topic is only created when it's published, that means if I set up a reader listening for a topic before the writer publish it, the reader never gets the `message` event.
The current logic is lookup nsqd with a specified topic, see: https://github.com/dudleycarr/nsqjs/blob/master/src/reader.coffee#L99-L100

Is it by designed? From [nsq document](http://nsq.io/overview/design.html) I found the following sentence which means topics should also be created when subscribing.

> Topics and channels are not configured a priori. Topics are created on first use by publishing to the named topic or by subscribing to a channel on the named topic.

**Comment by dudleycarr** [comment]
I don't think that documentation is accurate. I don't think it should be created when subscribing but I'm happy to defer to @mreiferson.

By the way, as it currently stands, there is no downside for a Reader to listen on a topic that hasn't been created on an `nsqd`. The Reader will happily poll `nsqlookupd` for topics and it will connect to the appropriate `nsqd`s once the topic is created and/or a message is published to that topic.

**Comment by xavierchow** [comment]
@dudleycarr Yes, I just need to wait for another `lookupdPollInterval` after the topics created by publishing, thanks for explanation.
