### ISSUE TITLE
maxAttempts option

### ISSUE THREAD

**Issue by xavierchow** [dudleycarr/nsqjs#109]
It seems the retry times is equal to `maxAttemps - 1`, e.g. if you set maxAttempts to 5, you only get 4 requeues and the 5th will go to DISCARD handler.
https://github.com/dudleycarr/nsqjs/blob/master/src/reader.coffee#L150

Is this  behaviour by designed? if so maybe it's better to clarify this in [document](https://github.com/dudleycarr/nsqjs#new-readertopic-channel-options).

**Comment by joshgummersall** [comment]
`maxAttemps` is the maximum number of times a single message will be attempted, not the number of requeues. As you observed, `requeues = maxAttempts - 1`. It does look like the documentation is not accurate on this so I went ahead and submitted a PR.

**Comment by xavierchow** [comment]
Thanks for heading up and clarification, I left a comment about the PR:https://github.com/dudleycarr/nsqjs/pull/110/commits/840a14b527c7625e7d4b3bda8ff7b1f736bf3e12#r72193870  maybe nitpicky tho 😄
