### ISSUE TITLE
Do u have plan to support lookupd_connect_timeout for consumer ?

### ISSUE THREAD

**Issue by zyvas** [dudleycarr/nsqjs#120]
Do u have plan to support lookupd_connect_timeout for consumer ?

**Comment by dudleycarr** [comment]
It makes sense and should be straightforward. Want to take a pass? Probably should support `lookupd_request_timeout` while we're at it.

**Comment by zyvas** [comment]
I read the source code, find out that `lookupd_request_timeout` is configured for 2 seconds.

In fact, I met a situation without a network, but the program did not show any exception. 

https://github.com/dudleycarr/nsqjs/blob/master/src/lookupd.coffee#L22

`lookupd` should be allowed to have an invalid time.

You probably don't need to do that.

thx.

**Comment by zyvas** [comment]
I connect to a nsqd by nsqlookupd, and cut off network for some time.

When the network is restored, the nsqd can't connect anymore.

**Comment by dudleycarr** [comment]
Closing. Should be addressed by #152
