### ISSUE TITLE
missing return statement

### ISSUE THREAD

**Issue by bcoe** [dudleycarr/nsqjs#135]
I'm fairly new to the codebase, so didn't want to make a change without fully understanding the intention -- but, it looks like there might be a missing return statement here:

https://github.com/dudleycarr/nsqjs/blob/master/src/reader.js#L90

without a return, it looks like two `setTimeouts` will be started?

**Comment by dudleycarr** [comment]
There is a the possible valid situation where you want to specify both an nsqd to connect to as well as discovering nsqd instances via lookupd. I'm not exactly sure why you would want to do this, but it's a possibility. Maybe @mreiferson has some thoughts about that for NSQ clients?

**Comment by mreiferson** [comment]
Yes, it's technically possible to configure it like that. I'm not sure it's very useful though.

**Comment by dudleycarr** [comment]
Thanks @mreiferson I think it's safe to leave it as it is.
