### ISSUE TITLE
setMaxListeners is not a function

### ISSUE THREAD

**Issue by sparkLogic** [dudleycarr/nsqjs#158]
Hello,

I'm attempting to run the sample project that uses npmjs with a local nsqd running. 
Prior to running the sample code, nsq was started with the recommended command line:
`nsqlookupd & nsqd -lookupd-tcp-address=127.0.0.1:4160`
Here is the code snippet:
```
var nsq = require('nsqjs');


var reader = new nsq.Reader('events', 'test_channel', {
  lookupdHTTPAddresses: '127.0.0.1:4161'
});

reader.connect();

reader.on('message', function (msg) {
  console.log('Received message [%s]: %s', msg.id, msg.body.toString());
  msg.finish();
});

var writer = nsq.Writer(':4151');

writer.connect();

writer.on('ready', function(){
    // topic is "event"
    // nsq-foo is the message being published in the event topic
    writer.publish('event', 'nsq-foo')
});

writer.on('closed', function() {
    console.log("NSQ writer closed");
});
```

This results in a `this.setMaxListeners(10000) is not a function` error as shown below with the DEBUG output:

>   DEBUG=nsqjs:* node index.js                                              
>   nsqjs:reader:events/test_channel Configuration +0ms
>   nsqjs:reader:events/test_channel ReaderConfig {
>   nsqjs:reader:events/test_channel   lookupdHTTPAddresses: [ '127.0.0.1:4161' ],
>   nsqjs:reader:events/test_channel   authSecret: null,
>   nsqjs:reader:events/test_channel   clientId: null,
>   nsqjs:reader:events/test_channel   deflate: false,
>   nsqjs:reader:events/test_channel   deflateLevel: 6,
>   nsqjs:reader:events/test_channel   heartbeatInterval: 30,
>   nsqjs:reader:events/test_channel   maxInFlight: 1,
>   nsqjs:reader:events/test_channel   messageTimeout: null,
>   nsqjs:reader:events/test_channel   outputBufferSize: null,
>   nsqjs:reader:events/test_channel   outputBufferTimeout: null,
>   nsqjs:reader:events/test_channel   requeueDelay: 90,
>   nsqjs:reader:events/test_channel   sampleRate: null,
>   nsqjs:reader:events/test_channel   snappy: false,
>   nsqjs:reader:events/test_channel   tls: false,
>   nsqjs:reader:events/test_channel   tlsVerification: true,
>   nsqjs:reader:events/test_channel   lookupdPollInterval: 60,
>   nsqjs:reader:events/test_channel   lookupdPollJitter: 0.3,
>   nsqjs:reader:events/test_channel   name: null,
>   nsqjs:reader:events/test_channel   nsqdTCPAddresses: [],
>   nsqjs:reader:events/test_channel   maxAttempts: 0,
>   nsqjs:reader:events/test_channel   maxBackoffDuration: 128 } +1ms
>   nsqjs:reader:events/test_channel:rdy ZERO +4ms
> /private/tmp/nsqd/node_modules/nsqjs/lib/writer.js:47
>     this.setMaxListeners(10000);
>          ^
> 
> TypeError: this.setMaxListeners is not a function
>     at Object.Writer (/private/tmp/nsqd/node_modules/nsqjs/lib/writer.js:47:10)
>     at Object.<anonymous> (/private/tmp/nsqd/index.js:15:18)
>     at Module._compile (module.js:573:30)
>     at Object.Module._extensions..js (module.js:584:10)
>     at Module.load (module.js:507:32)
>     at tryModuleLoad (module.js:470:12)
>     at Function.Module._load (module.js:462:3)
>     at Function.Module.runMain (module.js:609:10)
>     at startup (bootstrap_node.js:158:16)
>     at bootstrap_node.js:598:3 

Versions of node, npmjs:
```
node -v                                                               
v8.4.0
npm view nsqjs                                                               ✓  5250  18:44:56

{ name: 'nsqjs',
  description: 'NodeJS client for NSQ',
  'dist-tags': { latest: '0.8.4' },
  versions:
   [ '0.1.0',
     '0.2.0',
     '0.2.1',
     '0.2.2',
     '0.3.0',
     '0.3.1',
     '0.4.0',
     '0.4.1',
     '0.4.2',
     '0.5.0',
     '0.5.1',
     '0.6.0',
     '0.6.1',
     '0.7.0',
     '0.7.1',
     '0.7.2',
     '0.7.3',
     '0.7.4',
     '0.7.5',
     '0.7.6',
     '0.7.7',
     '0.7.8',
     '0.7.9',
     '0.7.10',
     '0.7.11',
     '0.7.12',
     '0.7.13',
     '0.8.0',
     '0.8.1',
     '0.8.2',
     '0.8.3',
     '0.8.4' ],
  maintainers: [ 'dudley <dudley.carr@gmail.com>' ],
  time:
   { modified: '2017-04-11T16:27:59.923Z',
     created: '2013-12-27T14:39:36.138Z',
     '0.1.0': '2013-12-27T14:39:36.138Z',
     '0.2.0': '2013-12-27T14:40:29.662Z',
     '0.2.1': '2013-12-30T20:35:02.342Z',
     '0.2.2': '2013-12-30T22:08:16.799Z',
     '0.3.0': '2014-01-08T16:24:12.351Z',
     '0.3.1': '2014-01-10T00:54:12.315Z',
     '0.4.0': '2014-02-17T21:51:19.979Z',
     '0.4.1': '2014-03-18T19:50:41.079Z',
     '0.4.2': '2014-05-14T20:27:43.953Z',
     '0.5.0': '2014-08-05T22:20:30.383Z',
     '0.5.1': '2014-09-15T20:51:45.037Z',
     '0.6.0': '2014-09-25T14:01:14.761Z',
     '0.6.1': '2014-10-10T11:18:00.223Z',
     '0.7.0': '2014-12-09T16:16:42.372Z',
     '0.7.1': '2015-02-10T04:32:58.055Z',
     '0.7.2': '2015-03-01T21:09:26.273Z',
     '0.7.3': '2015-03-14T19:20:39.879Z',
     '0.7.4': '2015-03-15T18:09:16.553Z',
     '0.7.5': '2015-03-15T20:23:13.133Z',
     '0.7.6': '2015-03-15T20:29:53.566Z',
     '0.7.7': '2015-09-13T03:55:01.051Z',
     '0.7.8': '2015-11-09T14:28:26.216Z',
     '0.7.9': '2015-12-22T18:35:10.965Z',
     '0.7.10': '2015-12-30T19:45:14.130Z',
     '0.7.11': '2016-03-24T19:06:33.309Z',
     '0.7.12': '2016-03-27T14:02:19.559Z',
     '0.7.13': '2017-01-02T23:25:09.658Z',
     '0.8.0': '2017-04-11T15:24:42.580Z',
     '0.8.1': '2017-04-11T15:25:43.379Z',
     '0.8.2': '2017-04-11T15:31:19.506Z',
     '0.8.3': '2017-04-11T15:34:41.704Z',
     '0.8.4': '2017-04-11T16:27:59.923Z' },
  readmeFilename: 'README.md',
  homepage: 'https://github.com/dudleycarr/nsqjs',
  keywords:
   [ 'nsq',
     'nsq client',
     'nsq client official',
     'nsqjs',
     'distributed messaging',
     'messaging',
     'task',
     'task management' ],
  repository:
   { type: 'git',
     url: 'git+https://github.com/dudleycarr/nsqjs.git' },
  author: 'Dudley Carr <dudley.carr@gmail.com>',
  bugs: { url: 'https://github.com/dudleycarr/nsqjs/issues' },
  users:
   { ghafran: true,
     gangleri: true,
     nevernet: true,
     dudley: true,
     ftopf: true,
     hengkiardo: true,
     ceejbot: true,
     menoncello: true },
  version: '0.8.4',
  licenses:
   [ { type: 'MIT',
       url: 'https://github.com/dudleycarr/nsqjs/blob/master/LICENSE-MIT' } ],
  main: 'lib/nsq',
  scripts:
   { build: 'coffee --bare --compile --output lib src/*.coffee',
     prepublish: 'coffee --bare --compile --output lib src/*.coffee',
     postpublish: 'rm -rf lib',
     test: 'grunt test' },
  engines: { node: '>= 0.10.0' },
  devDependencies:
   { 'coffee-errors': '^0.8.6',
     'coffee-script': '^1.12.2',
     coffeelint: '~1.0.2',
     grunt: '^1.0.0',
     'grunt-cli': '^1.2',
     'grunt-coffeelint': '0.0.16',
     'grunt-contrib-coffee': '^1.0',
     'grunt-contrib-watch': '^1.0.0',
     'grunt-mocha-cli': '^3.0.0',
     mocha: '^3.2',
     nock: '~0.27.1',
     should: '^11.1.2',
     sinon: '~1.7.3',
     temp: '^0.8.0' },
  dependencies:
   { async: '^2.1.4',
     'bignumber.js': '~1.2.1',
     debug: '^2.6.0',
     moment: '^2.17.1',
     'node-int64': '~0.3.0',
     'node-state': '~1.4.4',
     request: '^2.79.0',
     snappystream: '^0.3.4',
     underscore: '~1.5.2' },
  gitHead: '1c6b2aff3493bca7d515e722543dc5aeb3ad1566',
  dist:
   { shasum: '7c6d769b5f67ab7bc4a03eb2745f5f1fdf7e74b2',
     tarball: 'https://registry.npmjs.org/nsqjs/-/nsqjs-0.8.4.tgz' },
  directories: {} }
```

**Comment by sparkLogic** [comment]
@dudleycarr : can I provide any more information on this issue?

**Comment by adrianpike** [comment]
Hey @sparkLogic - it looks like you may be missing a `new` on this line of your code snippet;

```javascript
var writer = nsq.Writer(':4151');
```

I think it should be something like;

```javascript
var writer = new nsq.Writer(':4151');
```

**Comment by sparkLogic** [comment]
:duh: my bad. Resolving as operator error/stupidity.
