### ISSUE TITLE
Is there a mechanism in nsq client to detect logical connection lose?

### ISSUE THREAD

**Issue by abbshr** [dudleycarr/nsqjs#159]
such as a network device crash/down, in this situation, none of the endpoints know the connection will be disconnect only the nsqd could check the logical connection lost (by it live checking strategy). For the client, why not make use of the heartbeat ack to detect the connection? (Or, does nsqjs has builtin the same mechanism? I didn't find one. After network isolation, there is no timeout or close event triggered.)

**Comment by dudleycarr** [comment]
See NOP in the TCP spec:
http://nsq.io/clients/tcp_protocol_spec.html

**Comment by abbshr** [comment]
@dudleycarr The specs just describes the nsqd behaviors(How does nsqd treats the connection), I know the client will send ping cyclically to nsqd, but if no ack from `nsqd`, how does a client consider the current connection has been disconnected when there is no TCP `FIN` packet received and TCP keepalive is disabled in OS kernel? I think to add a idle timeout could be useful.

**Comment by dudleycarr** [comment]
@mreiferson thoughts?

**Comment by mreiferson** [comment]
In `go-nsq`, the `ReadTimeout` defaults to 60s which, if expired, would close the connection on the client side.

https://github.com/nsqio/go-nsq/blob/master/config.go#L98

**Comment by abbshr** [comment]
I have make a trick in my folk, but I think may be offical support is a better choice.

```js
// config.js
 static get DEFAULTS() {
    return {
      ...,
      idleTimeout: 0
    };
  }


// nsqdconnection.js
conn.setTimeout(this.config.idleTimeout * 1000, () => this.statemachine.raise('close'));
```

**Comment by dudleycarr** [comment]
@mreiferson Thanks for the pointer!

**Comment by dudleycarr** [comment]
@abbshr Thank you for the PR!
