### ISSUE TITLE
Reader.close() doesn't seem to work

### ISSUE THREAD

**Issue by tomc974** [dudleycarr/nsqjs#191]
Hi,

When I'm calling the `Reader.close()` method, it doesn't seem to disconnect from NSQ which causes my application to never terminate. I'm using:
* Node.js 8.6
* `nsqjs` 0.9.1

```javascript
const { Reader } = require('nsqjs')

const reader = new Reader('topic', 'channel', { nsqdTCPAddresses: 'localhost:4150' })

reader.on('nsqd_connected', () => {
  console.log('closing...')
  reader.close()
})

reader.on('nsqd_closed', () => { console.log('closed') })

reader.connect()
```

This code will outputs `closing...` and then hang indefinitely. So is this a bug or am I using the `Reader.close()` method incorrectly?

**Comment by dudleycarr** [comment]
Fixed in 0.9.2.
