### ISSUE TITLE
the Message class should be exported.

### ISSUE THREAD

**Issue by tomc974** [dudleycarr/nsqjs#195]
Hi!

I was trying to add some logging to my NSQ-based application with a code like the following:
```javascript
message.on('respond', (responseType, wireData) => {
  switch (responseType) {
    case Message.FINISH:
      // ...
      break

    case Message.REQUEUE:
      // ...
      break
  }
})
```

I received an error saying that `Message` is undefined, and that's normal since it's not exported by the module. Could you please export this class so we can use constants defined there?

**Comment by dudleycarr** [comment]
Sure, that's fine. I can do it later this week or if you're interested in opening a PR I can review sooner.
