### ISSUE TITLE
How to handle/catch `Error: E_TOUCH_FAILED TOUCH failed ID not in fligh`

### ISSUE THREAD

**Issue by againksy** [dudleycarr/nsqjs#201]
`Error: E_TOUCH_FAILED TOUCH 08cfae87c8852000 failed ID not in flight
    at NSQDConnection.receiveData`
Nsqjs node process crashes. How can i handle such errors or catch, to prevent crash of the node with nsqjs proccess?

**Comment by dudleycarr** [comment]
Listen for the `'error'` or `Reader.ERROR` event on the `Reader` instance.

```javascript
reader.on('error', err => { console.error(err) })
```

This will prevent the NodeJS process from crashing. However, you'll need to create a new Reader if you want to recover.
