### ISSUE TITLE
maxAttempts behaviour is erroneous

### ISSUE THREAD

**Issue by tomc974** [dudleycarr/nsqjs#203]
Hi!

While doing some testing, I found out that `maxAttempts = 1` won't allow my application to handle any message at all.

As far as I can tell, the problem is that NSQ starts the message `attempts` counter at 1 and that the condition in this driver is `this.config.maxAttempts <= message.attempts`. As a result, the driver works like that:
-  `maxAttempts = 0` means no limit
-  `maxAttempts = 1` means immediately discarded
-  `maxAttempts = 2` means discarded on the second attempts
-  ...

I strongly believe this behavior is erroneous and that the condition should be change to `this.config.maxAttempts < message.attempts`. Additionally, this is [how the official Go driver works], same for the [official Python driver behavior].

Of course this change would cause a BC break and should be heavily advertised once released.

[how the official Go driver works]: https://github.com/nsqio/go-nsq/blob/973bf9a2952ff7e38071ae8392b73e4418503059/consumer.go#L1142

[official Python driver behavior]: https://github.com/nsqio/pynsq/blob/53c65b832de82e22ef4bc9fc977a4188795f4b11/nsq/reader.py#L324

**Comment by dudleycarr** [comment]
Thanks for reporting this! Fixed in #204
