### ISSUE TITLE
Race condition when calling Reader.close() right after Reader.connect()

### ISSUE THREAD

**Issue by tomc974** [dudleycarr/nsqjs#207]
Hi!

I've noticed that if you call the `close` method of a reader right after you've received the `nsqd_connected` event, it may (rarely) happen that the connection won't be closed.

When the connection successfully closed, the debug log looks like this:
```
  nsqjs:reader:TestInput/TestChannel:conn:localhost/4150 IDENTIFY_COMPRESSION_CHECK +1ms
  nsqjs:reader:TestInput/TestChannel:conn:localhost/4150 AUTH +1ms
  nsqjs:reader:TestInput/TestChannel:conn:localhost/4150 SUBSCRIBE +0ms
  nsqjs:reader:TestInput/TestChannel:conn:localhost/4150 SUBSCRIBE_RESPONSE +1ms
  nsqjs:reader:TestInput/TestChannel:conn:localhost/4150 READY_RECV +2ms
(OMITTING SOME MESSAGES)
CALLING READER.CLOSE() FROM MY APP
  nsqjs:reader:TestInput/TestChannel:conn:localhost/4150 CLOSED +48ms
  nsqjs:reader:TestInput/TestChannel nsqd_closed +60ms
```

When it fails to close, the log looks like this:
```
  nsqjs:reader:TestInput/TestChannel:conn:localhost/4150 CONNECTING +0ms
  nsqjs:reader:TestInput/TestChannel:conn:localhost/4150 CONNECTED +9ms
  nsqjs:reader:TestInput/TestChannel:conn:localhost/4150 SEND_MAGIC_IDENTIFIER +1ms
  nsqjs:reader:TestInput/TestChannel:conn:localhost/4150 IDENTIFY +1ms
(OMITTING SOME MESSAGES)
  nsqjs:reader:TestInput/TestChannel:conn:localhost/4150 IDENTIFY_RESPONSE +13ms
  nsqjs:reader:TestInput/TestChannel nsqd_connected +39ms
CALLING READER.CLOSE() FROM MY APP
  nsqjs:reader:TestInput/TestChannel:conn:localhost/4150 IDENTIFY_COMPRESSION_CHECK +1ms
  nsqjs:reader:TestInput/TestChannel:conn:localhost/4150 AUTH +2ms
  nsqjs:reader:TestInput/TestChannel:conn:localhost/4150 SUBSCRIBE +1ms
  nsqjs:reader:TestInput/TestChannel:conn:localhost/4150 SUBSCRIBE_RESPONSE +0ms
  nsqjs:reader:TestInput/TestChannel:conn:localhost/4150 READY_RECV +2ms
```

To me, it looks like if I call the `close` method while the driver is still negotiating stuff about the connection, then the `nsqd_closed` event will not be emitted. To fix this issue, you could try to only emit the `nsqd_connected` after the `READY_RECV` message has been processed.

**Comment by dudleycarr** [comment]
If the user attempts to close the connection until it's in the ready state then it's ignored. If the underlying connection is closed, then it should be handled properly. Can you help me understand why you would want to call close on a Reader instance that hasn't finished connecting?

**Comment by tomc974** [comment]
I never meant to call `close()` before the reader has finished connecting. My expectation was that once the `nsqd_connected` event has been received then the reader _had finished_ connecting which turns out to be wrong.

I found out about this will writing integration tests for a component which should emit `started` and `stopped` events when internal reader have finished connecting and disconnecting respectively.

So one of my mocha test for this component looked like this:

```javascript
  it('should emit stopped event after stop() has been called', function (done) {
    const component = new Component(/* settings... */)
    component.on('started', () => component.stop())
    component.on('stopped', done)
    component.start()
  })
````

The issue was that my component fired the `started` event right after the reader fired the `nsqd_connected` event, which in turn called the component `stop()` method. This method asked the internal reader to close its connection before emitting the `stopped` event. Of course, the test failed. After some investigation I've found out what caused the issue and fixed it with a simple workaround:

```javascript
    // Delay stop() to be sure the internal reader is actually ready
    component.on('started', () => setTimeout(() => component.stop(), 50))
```

Of course, outside an integration test, I don't expect the reader behavior to be a real issue but you should either document that the `close` method does nothing when called at the wrong time or delay the `nsqd_connected` until the reader has finished handshaking stuff with the server. I'm not sure what the implication would be if connecting to multiple `nsqd` since I haven't tested this scenario yet.

**Comment by dudleycarr** [comment]
Thanks for the explanation. The `NSQD_CONNECTED` event, as you discovered, just indicates that a connection has been made and not that the connection has been fully negotiated. It might be useful to emit a READY event for a connection for situations like this.

The implication for multiple NSQDs and the `close` behavior does raise a good point. Each connection has its own state machine, and that state machine would ignore the close action if it's busy negotiating. There could a situation where the Reader discovers a new NSQD connect to and at the same time the client chooses to close the Reader leading to the underlying connection not closing due to the timing. That would certainly warrant modifying the state machine to support close while a connection is being negotiated.

**Comment by joernroeder** [comment]
expected the same behaviour as @tomc974. A `READY` event would clarify it
