### ISSUE TITLE
Memory leak caused by debug.js

### ISSUE THREAD

**Issue by djelusic** [dudleycarr/nsqjs#211]
I am experiencing a memory leak in one of our production applications using nsqjs. After doing some memory profiling it seems the issue is connected with the debug package:

![heap](https://user-images.githubusercontent.com/7542377/34773785-35ea92ce-f60d-11e7-9130-ad318632694f.png)

After having a glance at the source it seems that every time an NSQDConnection is created it initialises a debug object ([nsqdconnection.js:109](https://github.com/dudleycarr/nsqjs/blob/b700e9feb2a469686e03b92fc02165415338bf6e/lib/nsqdconnection.js#L109)) which then gets added to an array ([common.js:134](https://github.com/visionmedia/debug/blob/22f993216dcdcee07eb0601ea71a917e4925a30a/src/common.js#L134)). This is never cleaned up. There is a destroy function provided ([common.js:139](https://github.com/visionmedia/debug/blob/22f993216dcdcee07eb0601ea71a917e4925a30a/src/common.js#L139)) which is never used.

Previously we were using a fork of nsqjs based on v0.8. The issue was not present there. I noticed that in the meantime debug.js was updated to a newer version (2.6.1 -> 3.0.1, [9ec579f](https://github.com/dudleycarr/nsqjs/commit/9ec579f0a55f25ad5836ec5d08a55c23fb9a04d0#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L58))

**Comment by dudleycarr** [comment]
Interesting. Would you mind opening a PR?

**Comment by dudleycarr** [comment]
Fixed in version 0.10.1. Live on npm. Thanks!
