### ISSUE TITLE
How do we create a topic and its channel? 

### ISSUE THREAD

**Issue by dg92** [dudleycarr/nsqjs#216]
Fairly new to this.

I just read nsq today and it feels amazing, but i wonder how do we create topic and channels using nsqjs or do we need to create manually by curl ?

I am totally new to this, if somebody can help getting started with it like
1. Create topic and channels
2. How do we add data to nsqd, in my case, i have an api that send some data and i need to enqueue it and later on some worker/consumer will dequeue and work accordingly on them.

I tried doing a bunch of stuff but didn't have success creating topics and its channel, any reference is highly appreciated.

Need help!

**Comment by dudleycarr** [comment]
You can create topics by either publishing a message or by explicitly creating a topic on an nsqd ( http://nsq.io/components/nsqd.html#post-topiccreate ). When you specify the topic for the message, the topic is implicitly created. A channel is implicitly created when a Reader connects to a nsqd. The Reader has to specify the topic and the channel.

**Comment by dg92** [comment]
@dudleycarr how do i publishing a message using this package?
