### ISSUE TITLE
timeouts too short...

### ISSUE THREAD

**Issue by jhiver** [dudleycarr/nsqjs#232]
Looks like your 5 sec is actually 0.5 sec :-) 

          // Once there's a socket connection, give it 5 seconds to receive an
          // identify response.
          this.identifyTimeoutId = setTimeout(() => {
            this.identifyTimeout()
          }, 500)

**Comment by dudleycarr** [comment]
Good catch!

**Comment by emaincourt** [comment]
@dudleycarr we are actually getting trouble with this short timeout in production. I opened a pull request to fix it : https://github.com/dudleycarr/nsqjs/pull/233 :)
