### ISSUE TITLE
new nsq.Reader how can i get the port which the Reader process listening?

### ISSUE THREAD

**Issue by triesa** [dudleycarr/nsqjs#251]
is there  a way to get port on which the Reacers listening?
I need to get the port on which the reader listens for messages from nodejs nsq reader instance

**Comment by triesa** [comment]
@dudleycarr , but they have port on which the receive messages, or how do the connected?

**Comment by dudleycarr** [comment]
You would see the same thing if you had an HTTP client connecting to an HTTP server on port 80. The client always has some randomly assigned port, but it's really of no use typically in the application layer.

The Reader receives messages on the connection after connecting to NSQD typically on port 4150. 

What would be the use of getting the underlying connection port for the Reader?

**Comment by triesa** [comment]
@dudleycarr i have many nodejs processes with nsq reader inside.

And i wish to enable some loggign for them, i gonna use winston, and i want , when node reader process start- write their logs in separate folders named by example `reader_57109` -`reader_$PORT(or maybe some $identificator)` .  Maybe i choosed wrong way for this?

Maybe i can use some other identificator for this? 

Can you suggest something about how to realize  logging for each process separately?

Beacause i wish to understand which message process was broken in reader in case with errors.

Maybe i should get the pid inside reader process and use this?

Maybe you know some solutions for logging many listeners? What is the right way?

**Comment by dudleycarr** [comment]
I think your best bet would be to use a combination of the hostname and say PID or a randomly generated ID. Whatever ID you generated, I'd also recommend passing that to the Reader as the clientId which will help you if you need to correlate `nsqd` logs with your own.

I'm marking this as closed as this doesn't seem to be an issue with nsqjs.
