### ISSUE TITLE
concurrency: share max_in_flight across multiple readers of single consumer

### ISSUE THREAD

**Issue by apmcodes** [dudleycarr/nsqjs#256]
Is there a way for a consumer to receive a fixed number of messages whether it instantiates 1 or more reader instances. Say at any time a consumer receives a maximum of 1000 messages with variable number of readers (between 1 and 5) reading from different topics. So if i run a reader instance the consumer will receive maximum 1000 messages at a time and if I add another reader instance then still this consumer will receive maximum 1000 messages at a time. 

Currently, if a node process (a consumer) runs a reader instance with max_in_flight value of 2 then it receives 2 messages at a time and for each additional readers the consumer initialises, it receives 2 more messages. 

Also, is it possible to dynamically change maxInFlight of a reader after initialisation?

**Comment by dudleycarr** [comment]
It's possible but not functionality nsqjs provides out of the box. Can you help me understand what you're trying to do?

**Comment by apmcodes** [comment]
We are trying to deliver emails that are queued in multiple topics (say 10), so 10 readers will fetch from each topic. So at a time more than 1 reader will be fetching messages from nsqd and we need to CAP the maximum number of message received by a SINGLE node process so not to overwhelm smtp connections. 

Setting max_rdy_count = 1000 in nsqd and maxInFlight = higher than max_rdy_count (say 10000) in all the readers helped receive maximum of 1000 messages, irrespective of the number of readers in a consumer (single node process). This has achieved our requirement.

**Comment by apmcodes** [comment]
The emails belongs to various jobs, so we need a way to pause/ resume/ cancel jobs. If the emails all are on their own topic/ queue then we can just operate on them easily.

**Comment by dudleycarr** [comment]
I see. Those topics are for workers that generate an email to be sent and each of the workers, I presume, is generating a different kind of email. Why not have those workers generating the email but instead of sending it to the SNMP server, publish it to a topic, and have a single worker then relay those to the SNMP server? That will give you better control of the concurrency than what you have now. It will also separate the email generation work from the sending work which might be handy.

**Comment by apmcodes** [comment]
Thank you for the suggestion and taking the time to explain. I got your point that its easier to manage concurrency with a single reader. But managing concurrency with multiple, dynamic number of readers is presenting the problem. 

Email delivery is distributed among different workers to maintain IP reputation and other SMTP/ ISP related reasons. So, there needs to be multiple workers (up to 30 servers) and they will do the actual delivery of the emails (by connecting to various SMTP servers). Each worker will be assigned multiple topics (Jobs), anytime. So a single worker needs multiple readers to subscribe to each topic, among these readers we need to cap the in flight messages (in short, from a single worker/ server no more than 1000 smtp outgoing connections are made). (Just for clarification, in beanstalkd, using a single connection/ reader one can subscribe to multiple topics and pull messages from those topics). 

Btw, in my previous posts suggestion of setting max_rdy_count and maxInFlight fixes concurrency of 1000 across multiple readers (in a worker/ server), but it involves nsqd level configuration and to change it we need to restart nsqd. Also it does not allow for setting different concurrency for different readers. 

So, is there a better option to achieve the above requirement of fixing a maximum messages across readers? 

Thanks once again for your suggestions.
