### ISSUE TITLE
How to publish message with channel?

### ISSUE THREAD

**Issue by slaveofcode** [dudleycarr/nsqjs#258]
I've been reading the documentation of writer but couldn't find any documentation about how to publish to specific channel programmatically

**Comment by dudleycarr** [comment]
You can’t. nsq has you publishing to topics and that same message goes to all channels for that topic. I’d recommend taking a closer look at the nsq documentation.

**Comment by gubeils** [comment]
@dudleycarr If channel cannot be used, what is their purpose and how are they supposed to be used?
