### ISSUE TITLE
Can't tls handshake with two-way verification

### ISSUE THREAD

**Issue by andrey-avdeev** [dudleycarr/nsqjs#259]
const w = new nsq.Writer('localhost', '4150', {
    tls: true,
    tlsVerification: true,
    key: fs.readFileSync('certs/client1-key.pem'),
    cert: fs.readFileSync('certs/client1-crt.pem'),
    ca: fs.readFileSync('certs/ca-crt.pem')
Throwing error - ca must be an array.

**Comment by dudleycarr** [comment]
Fixed in #260
