### ISSUE TITLE
Possible memory leak in nsqjs writer

### ISSUE THREAD

**Issue by tsde** [dudleycarr/nsqjs#268]
Hi,

I'm using NodeJS 11.5.0 did a simple benchmark of the nsqjs Writer (v0.12.0) and found a possible memory leak, possibly the same kind as in https://github.com/dudleycarr/nsqjs/issues/211 which was related to the nsqjs Reader. You'll find attached the `app.js` script I used for testing as well as the `package.json` and `test.json` file. Basically, it uses nsqjs Writer as a middleware for Koa (code was mostly taken from https://github.com/dudleycarr/nsqjs/issues/202#issuecomment-346075638). For the benchmark, I simply used a `while true` loop with curl, sending a small json content as POST data to the Koa endpoint (example: `while true; do curl -XPOST -d @test.json http://127.0.0.1:3000/test -H 'Accept: application/json' -H 'Content-Type: application/json'; done`).

Below is the result of the heap profiling. Heap snapshots were taken every 10 minutes. As you can see, the heap grows quite rapidly (from ~20 to ~140 MB). Apparently, this seems related to the debug module.

![heapdump_leak](https://user-images.githubusercontent.com/11899826/50494302-cca45b80-0a22-11e9-98d7-6c0a06ddf87f.png)

To confirm this, I did something really dirty but effective. I commented out every mention to the debug module in `nsqdconnection.js` and `writer.js` and went through the same process. Heap profiling result is below. In this case, the heap is stable. 

![heapdump_ok](https://user-images.githubusercontent.com/11899826/50494593-85b76580-0a24-11e9-94c0-707a8d4022bf.png)

I'm far from being a NodeJS guru though ;). So if I'm missing something important or if my testing code is buggy, don't hesitate to tell me. Still, it really looks like the same behavior as in https://github.com/dudleycarr/nsqjs/issues/211

[app.zip](https://github.com/dudleycarr/nsqjs/files/2713397/app.zip)

**Comment by ilikegolf** [comment]
Hello! I am also still seeing this behavior 4 years after the original issue was posted.  Is this library still being maintained?

**Comment by dudleycarr** [comment]
@ilikegolf I'll take a look this week to see if I can reproduce the issue.

**Comment by dudleycarr** [comment]
The issue is a missing explicit call to destroy the debug connection. It should go here:
https://github.com/dudleycarr/nsqjs/blob/main/lib/writer.js#L179

```
this.debug.destroy()
```

Would you mind trying that out? If that fixes the issue for you, then I'll open a PR and cut a release.

By the way, I would recommend not creating a new Writer for each message to be sent to the nsqd instance. Ideally, you create the connection once and then re-use it on each HTTP request. That said, glad you were able to discover the debug memory leak though.

**Comment by ilikegolf** [comment]
Oh-that is how I use the Writer class. I have one instance and over time the memory usage builds and builds until it runs out of memory and crashes.  The Reader class shows stable memory usage over time.

**Comment by ilikegolf** [comment]
After further investigation, I do not believe my memory leak was caused the`nsqjs:Writer` class. However, thank you so much for your responsiveness @dudleycarr.
