### ISSUE TITLE
What happens if we doesn't close the connection after doing message publication?

### ISSUE THREAD

**Issue by slaveofcode** [dudleycarr/nsqjs#269]
Currently, I have a simple function which opens a new connection when it's called, the function look like this

```
const publisher (clientId = null) => {
  const nsqHost = process.env.NSQ_HOST
  const nsqPort = process.env.NSQ_PORT

  const opts = {}
  if (clientId) opts.clientId = clientId
  const writer = new nsq.Writer(nsqHost, nsqPort, opts)
  writer.connect()

  return {
    onReady: cb => {
      try {
        cb(writer)
      } catch (err) {
        console.error(err.message)
      }
    },
  }
}

function one() {
    publisher('foo').onReady(writer => {
      writer.publish('message', "Hello One")
    })
}

function two() {
    publisher('foo').onReady(writer => {
      writer.publish('message', "Hello Two")
    })

}

function main() {
    one()
    two()
}
```

My question is, 

1. Are these approach right to do?  
2. Should I suppose to close the connection once I publish a message?
3. Are there recommended patterns when I constantly publish a message without re-creating a new connection?

**Comment by dudleycarr** [comment]
You ideally want to re-use the same Writer if you're sending a lot of messages otherwise you could just as easily do an HTTP POST call to an NSQD instance to deliver your message. So, no, the suggested approach above isn't ideal.

**Comment by slaveofcode** [comment]
@dudleycarr thanks for the answer
