### ISSUE TITLE
No callback or event for message finish?

### ISSUE THREAD

**Issue by apmcodes** [dudleycarr/nsqjs#272]
Read the docs and code, seems there is no to callback or FINISH event.

**Comment by apmcodes** [comment]
Okay. Just wanted to catch if there was any error in finishing the message. Nothing else.

**Comment by dudleycarr** [comment]
The server doesn't acknowledge a finish. The client shouldn't really care either. Let's say the finish got lost along the way. In that case, the server would have that client or another client re-attempt the message. Given that design, it doesn't make sense for clients to really know that the message was finished with respect to the server. I hope that helps.

**Comment by apmcodes** [comment]
That makes it clear. Btw, we have a type of task that's idempotent so was trying to add an extra function to make sure finish is called. 

Thanks for the clarification ...
