### ISSUE TITLE
Support for Node V12

### ISSUE THREAD

**Issue by heathcliff-hu** [dudleycarr/nsqjs#285]
The sse4_crc32 does not to support Node V12.

The issue comes from sse4-crc32.

See anandsuresh/sse4_crc32#74

**Comment by dudleycarr** [comment]
It looks like they're trying to resolve the issue at the moment :| Are you unable to install nsqjs at the moment?

**Comment by fancy-rabbit** [comment]
@dudleycarr unable to install nsqjs on node12, either.

**Comment by dudleycarr** [comment]
This will get fixed as soon as anandsuresh/sse4_crc32#75 gets merged.
