### ISSUE TITLE
bignumber.js constructor error.

### ISSUE THREAD

**Issue by ishan-ghorela** [dudleycarr/nsqjs#330]
Build fails because of BigNumber.js dependency. I have verified this dependency is added in node_modules 

` this.minInterval = new BigNumber(minInterval)`

`TypeError: BigNumber is not a constructor`

BigNumber.js official documentation says it should be imported as
`const BigNumber = require('bignumber.js');`

but in `node_modules/nsqjs/lib/backofftimer.js` it is 
`const { BigNumber } = require('bignumber.js')` 

but changing this import doesn't solve the problem

<img width="777" alt="Screenshot 2021-04-09 at 4 50 48 PM" src="https://user-images.githubusercontent.com/64069537/114173081-30cd5e00-9954-11eb-9bf2-9f740cd14284.png">

**Comment by dudleycarr** [comment]
What version of node are you using?

**Comment by ishan-ghorela** [comment]
node `v12.18.4`

**Comment by ishan-ghorela** [comment]
@dudleycarr any suggestions ?

**Comment by dudleycarr** [comment]
I noticed some webpack output. Are you using webpack for a server side project? Could you share a minimal project which reproduces the issue?

**Comment by ishan-ghorela** [comment]
yes we are using webpack.

**Comment by ishan-ghorela** [comment]
@dudleycarr I am afraid I wont be able to share the project but can you suggest what can be wrong ?

**Comment by dudleycarr** [comment]
Can you explain why you're building a server side app with webpack? That's a bit unusual.

**Comment by ishan-ghorela** [comment]
we have server and client inside the same repository so we use the same tool for server as well.

**Comment by ishan-ghorela** [comment]
@dudleycarr  but rest of the dependencies work fine with webpack build, is there any issue with nsqjs and how can we fix it ?

**Comment by dudleycarr** [comment]
Can you share your webpack config?

**Comment by dudleycarr** [comment]
I removed the dependency on BigNumber in #337. Can you try what's on `main` and let me know if that resolves the issue?

**Comment by ishan-ghorela** [comment]
Thanks for the update @dudleycarr . I am out of office today. I will update you by tomorrow

**Comment by ishan-ghorela** [comment]
@dudleycarr tried deleting and reinstalling the `nsqjs` package. Still getting the old files with Bignumber.js . Can you pls change the version as well ?

**Comment by dudleycarr** [comment]
Please update your package.json to point to the GitHub repo. I'd like to confirm it's fixed before doing releases.

**Comment by dudleycarr** [comment]
https://medium.com/@jonchurch/use-github-branch-as-dependency-in-package-json-5eb609c81f1a

**Comment by ishan-ghorela** [comment]
ok. let me check this

**Comment by ishan-ghorela** [comment]
@dudleycarr unfortunately it's another error now related to `async` dependency.

` return async.map(urls, lookupdRequest, (err, results) => {
^
TypeError: async.map is not a function`

<img width="699" alt="Screenshot 2021-04-15 at 11 27 01 AM" src="https://user-images.githubusercontent.com/64069537/114821020-8e8ef980-9ddd-11eb-9ab6-e7dacefe8ded.png">

**Comment by dudleycarr** [comment]
@ishan-ghorela I tried using webpack locally to build a bundle with nsqjs as a dependency. There are too many issues to resolve with bundling a nodejs app. While I'd like to help, this isn't a common approach for nodejs apps and there are other improvements to nsqjs that are a higher priority to me.

I would be happy to make the necessary changes provided you invest the time to figure out the particulars of your build setup and nsqjs.

**Comment by ishan-ghorela** [comment]
yes @dudleycarr , I totally get it. For now we have moved to new nodejs service without webpack.  Thanks for your support
