### ISSUE TITLE
debug.destroy call not available on npm (bump version?)

### ISSUE THREAD

**Issue by icetbr** [dudleycarr/nsqjs#342]
Hi, regarding this I think https://github.com/dudleycarr/nsqjs/pull/336.

I still see this when I `npm i` version 0.12.1

node_modules/nsqjs/lib/reader.js:192
```js
    // Ensure a connection doesn't already exist to this nsqd instance.
    if (this.connectionIds.indexOf(conn.id()) !== -1) {
      conn.debug.destroy()
      return
    }
```

**Comment by dudleycarr** [comment]
Please re-open if this is still an issue in `0.13.0` or later.
