### ISSUE TITLE
setTimeout().unref() is not a function in Electron

### ISSUE THREAD

**Issue by ulfeng** [dudleycarr/nsqjs#386]
Electron version: 8.0.0
Operating system: Mac OS
<img width="552" alt="image" src="https://user-images.githubusercontent.com/10446666/167119379-573501f3-a558-4b24-8801-1d9273f655af.png">

**Comment by dudleycarr** [comment]
`unref` is NodeJS specific. If you're using in the context of the browser, that will not work.
