### ISSUE TITLE
How can I associate a channel when publishing to NSQ? I'm not sure how to use channels correctly. Are there any articles or documentation that explain this?

### ISSUE THREAD

**Issue by gubeils** [dudleycarr/nsqjs#430]

**Comment by dudleycarr** [comment]
Take a look at the official NSQ documentation: https://nsq.io/overview/design.html

When you publish a message to a topic, it fans out the message to all the topic's channels. There are a couple of ways to create a channel, but the most common is to create a Reader with the topic/channel pair.
