### ISSUE TITLE
callback from writer.publish() isn't invoked on failure

### ISSUE THREAD

**Issue by bsphere** [dudleycarr/nsqjs#53]
when writing a message that fails with the following scenarios, the callback from `publish()` isn't invoked at all.

1) nsqd is down, publish a message
2) nsqd is up, writer connects, nsqd is down, publish a message
3) nsqd is up, writer connects, nsqd is down, nsqd is up, publish a message (this is actually fixed in my pull request)

the expected behavior is an invoked callback with err from `writer.publish()`,
there is no way to know if a message publish failed otherwise

**Comment by dudleycarr** [comment]
Fixed in #64
