### ISSUE TITLE
Snappy compression not supported for nsqlookupd

### ISSUE THREAD

**Issue by Bondza** [dudleycarr/nsqjs#54]
According to the [nsqlookupd documentation](http://nsq.io/components/nsqlookupd.html), there is no option to specify support for snappy compression, there is however an option to specify the use of snappy compression for an nsqjs Reader. Specifying the snappy option for a Reader seems to result in an error, as shown by the log messages below.

```
04 15:26:50.095397 [10.12.9.74:36747] IDENTIFY: {ShortId:a66c72088fd9 LongId:a66c72088fd9 ClientID:a66c72088fd9 Hostname: HeartbeatInterval:30000 OutputBufferSize:0 Outpu
04 15:26:50.095775 PROTOCOL(V2): [10.12.9.74:36747] upgrading connection to snappy
04 15:26:50.117902 PROTOCOL(V2): [10.12.9.74:36747] exiting ioloop
04 15:26:50.117960 ERROR: client(10.12.9.74:36747) - failed to read command - read tcp 10.12.9.74:36747: connection reset by peer
04 15:26:50.118546 PROTOCOL(V2): [10.12.9.74:36747] exiting messagePump
```

So should the snappy compression option work for a reader or is the documentation for nsqjs incorrect?

**Comment by dudleycarr** [comment]
It should work. Are you running the latest version of nsq?

**Comment by dudleycarr** [comment]
Can you also reply with the nsqd parameters that you're using?

**Comment by Bondza** [comment]
We're running version 0.3.0 of nsq. And the nsqlookupd parameters are ```-broadcast-address=<ip>```.
But like I said before, according to the documentation of nsqlookupd there is no snappy compression option available, and it seems like nsqlookupd just exits with an error message whenever you specify it.
```
nsqlookupd -snappy
flag provided but not defined: -snappy
Usage of nsqlookupd:
  -broadcast-address="": address of this lookupd node, (default to the OS hostname)
  -config="": path to config file
  -http-address="0.0.0.0:4161": <addr>:<port> to listen on for HTTP clients
  -inactive-producer-timeout=5m0s: duration of time a producer will remain in the active list since its last ping
  -tcp-address="0.0.0.0:4160": <addr>:<port> to listen on for TCP clients
  -tombstone-lifetime=45s: duration of time a producer will remain tombstoned if registration remains
  -verbose=false: enable verbose logging
  -version=false: print version string
```

**Comment by dudleycarr** [comment]
You can only specify the snappy option on nsqd, not nsqlookupd. nsqjs only
discovers nsqds via nsqlookupd. The actual connection negotiation happens
with the nsqd and it obviously depends on the options turned on when nsqd
was started. I hope that helps.
