### ISSUE TITLE
Expose request module options

### ISSUE THREAD

**Issue by saidimu** [dudleycarr/nsqjs#56]
Currently it isn't possible to tweak the `request` module's options, for example to increase `maxSockets` (the NodeJS default of 5 is too low if you need a greater number of concurrent requests. In Node v0.12 this now defaults to `Infinity`).

Setting `http.globalAgent.maxSockets` isn't always desirable since it will affect all `http` requests in the process. And it doesn't always work depending on whether you specified a custom agent to `request`.

**Comment by dudleycarr** [comment]
I'm open to proposals. However, I think everyone is acknowledging the fact that the maxSocjet limit in the first place was a half baked idea and thus the move to be at infinity. It seems wise to me to do so for anything below 0.12.

**Comment by saidimu** [comment]
The challenge with changing the options for <v0.12 is that it might bite people who unknowingly depended on the settings for rate-limiting. Their apps would suddenly generate as many requests as the OS can handle whereas previously it only generated 5 at a time.

**Comment by dudleycarr** [comment]
Closing this for now until I run into someone who is still running `< 0.10` and wants this option.
