### ISSUE TITLE
Close reader without discarding in flight messages

### ISSUE THREAD

**Issue by Bondza** [dudleycarr/nsqjs#68]
When I close my application I would like to close the reader and make sure all messages are processed before my application terminates. As Reader.close() does not care about messages in flight, this is not possible, at least not in a nice way.

I guess I could pause, wait for a while and then close, but there is still no way of knowing that all messages was actually processed. It would be nice if I could pause and get an event when the number of messages in flight reaches zero and then close my reader.

Is there any reason there is no "end of message flow"-event today?

**Comment by dudleycarr** [comment]
It's possible to do this with the current implementation of nsqjs. It might be worthwhile to make this part of the Reader. However, here's a solution for you based on the current version. I unfortunately haven't tested it, but conceptually I believe it's sound.

```coffee-script
_ = require 'underscore'
async = require 'async'
nsq = require 'nsqjs'

class Drain

  constructor: (@reader) ->
    @msgs = {}
    @drainCallback = null

    # Track reader messages received and finished. If no more messages are
    # tracked, then close the reader.
    @reader.on 'message', (msg) ->
      @msgs = msgs[msg.id]

      removeMessage = (msg) ->
        delete @msgs[msg.id]

        # Final cleanup if we're done with the last message
        if _.isEmpty @msgs and @drainCallback?
          reader.close()
          @drainCallback()

          # Remove references.
          @msgs = {}
          @drainCallback = null

      msg.on 'respond', (responseCode) ->
        # Finish or Requeue responses
        if responseCode in [0,1]
          removeMessage msg

    @reader.on 'error', (err) ->
      @drainCallback err if @drainCallback?

  close: (callback) ->
    unless _.isFunction callback
      return new Error('Callback needed for Drain.close')

    if _.isEmpty @msgs
      # No message in-flight -- close immediately.
      reader.close()
      callback null
    else
      # Pause, wait for in-flight messages to finish, and then close.
      @reader.pause()
      @drainCallback = callback
```

**Comment by Bondza** [comment]
Alright, that's true it's not impossible. But I think it would be a bit nicer if this was part of the Reader.
 
Anyways, I'll try it out. Thanks!

**Comment by dudleycarr** [comment]
I'll like just had a drain method on the Reader class to make this straightforward. Thanks for suggesting this.
