### ISSUE TITLE
Error: Timed out identifying with nsqd

### ISSUE THREAD

**Issue by liuhui244671426** [dudleycarr/nsqjs#73]
code:

var nsq = require('nsqjs');
var options = [false, true, false, 6, false, 1];
var w = new nsq.Writer('192.168.1.17', 4151);

w.connect();

w.on('ready', function () {
  console.log('ready');
  w.publish('test', 'hello world2!', function (err) {
    if (err) { return console.error(err.message); }
    console.log('Message sent successfully');
    w.close();
  });
});
 
w.on('closed', function (e) {
  console.log('Writer closed');
});

w.on('error', function(err){
  console.trace(err);
});

Trace: [Error: Timed out identifying with nsqd] 
why?

**Comment by dudleycarr** [comment]
You're using the wrong port. Try 4150.

**Comment by liuhui244671426** [comment]
thanks
