### ISSUE TITLE
Is maxAttempts: 0 safe?

### ISSUE THREAD

**Issue by fizerkhan** [dudleycarr/nsqjs#74]
Recently i encountered a problem of sending more than 500 emails to my customer because it gets requeued continuously. It just because maxAttempts set to 0 by default. I don't know why you set maxAttempts to zero. 

Can we set maxAttempts to 50-100? (or) We should mention the importance and include this option in the sample code in the Readme. Let me know your thoughts.

**Comment by dudleycarr** [comment]
It's probably something that we can clarify in the documentation.
