### ISSUE TITLE
Support for Node 4.0.0

### ISSUE THREAD

**Issue by Gank** [dudleycarr/nsqjs#76]
As expected, some of the required dependencies don't seem to support Node 4.0.0.

**Comment by dudleycarr** [comment]
Will take a look shortly!

**Comment by shinzui** [comment]
I get a "Segmentation fault: 11" while running tests which rely on nsqjs under node 4.0.0.

**Comment by dudleycarr** [comment]
`nsqjs` depends on `snappystream` which in turn depends on `snappy` and
sse4_crc32`. Both of those last two dependencies need to have their
versions bumped in snappystream for things to work with Node V4.
Unfortunately, both seem to be having issues building on travis for all
versions of nodejs / iojs after node-gyp and nan have been updated.
Hopefully those issues will be resolved soon.

**Comment by ChALkeR** [comment]
Adding to the list: https://github.com/nodejs/node/issues/2798.
