### ISSUE TITLE
timestamp as date

### ISSUE THREAD

**Issue by raine** [dudleycarr/nsqjs#83]
As I understand `message.timestamp` represents when the message was first created.

What is the correct way to convert the `BigNumber` into a `Date` object? Purpose is just to make it more readable in logs.

All I could think of was `new Date(parseInt(message.timestamp.toString().slice(0, 13)))` which doesn't seem that great.

Also just wondering if there's any particular reason nsqjs itself doesn't provide the timestamp as a `Date` object?

Cheers.

**Comment by dudleycarr** [comment]
The message class exposes the raw value provided by nsq. The nsq docs say that the timestamp is defined in nanoseconds. You'll likely have to convert it into a BigNumber and then divide by `1000` to convert it into a JavaScript Date object.
