### ISSUE TITLE
question about usage

### ISSUE THREAD

**Issue by joeblew99** [dudleycarr/nsqjs#88]
I am using NSQ for micro services. Its all golang.

I am looking for a layer on top of this, that allows web browsers to send and receive JSON data from the NSQ based micro services. The micro services do not speak HTTP; they only talk amongst themselves over the NSQ topics / channels.

**Comment by dudleycarr** [comment]
So, nsqjs is not meant to be run in a browser. I'm inferring that's what you were hoping for. The best solution given your requirements would be a process that uses SocketIO to bridge the front-end and NSQ.

**Comment by joeblew99** [comment]
yep you inferred right :)

I more exploring the best way to share types between the 3 layers:
- browser
- http proxy (HTTP and WS)
- NSQ

**Comment by dudleycarr** [comment]
In my experience, thinking of NSQ as an RPC layer leads to all kinds of problems. Topics as functions leads to some pretty complex pipelines. Debugging becomes a bear when there's a failure. Something to consider.

**Comment by joeblew99** [comment]
exactly what i am thinking. thansk for the feedback.

I will  close this.
