### ISSUE TITLE
Memory overflow problem

### ISSUE THREAD

**Issue by kerngven** [dudleycarr/nsqjs#95]
![63 pic](https://cloud.githubusercontent.com/assets/3096073/12135265/72228256-b474-11e5-89cf-6b4acbc2f0dc.jpg)
hello:
maybe network is very bad, write message is so much. 
maybe array (this.conn.messageCallbacks) length is unlimited.
the process memory will increase
Is there any way to solve it?

Whether it can be like this?
typeof callback === "function" ? this.conn.messageCallbacks.push(callback) : false;

I didn't find the write about the timeout parameters.

**Comment by dudleycarr** [comment]
You can listen for underlying socket disconnects if you want better control in the event that a connection gets dropped and messages backup. This approach is somewhat naive, but probably fine in the vast majority of cases.
