### ISSUE TITLE
Move source to ES2015

### ISSUE THREAD

**Issue by hilkeheremans** [dudleycarr/nsqjs#96]
A matter that pops up in more and more CoffeeScript based projects: in order to facilitate community contribution to ```nsqjs``` I would suggest a move from CoffeeScript to ES2015.

The conversion in itself shouldn't be too hard to do, but it could just as well be a good opportunity to refactor should it be needed or take some other wins or features along.

Let me guess, will you be replying "go ahead and submit a PR"? :-) Thing is, I'm willing to spend some time on this, but can't until a few months from now at the earliest.

**Comment by dudleycarr** [comment]
I appreciate the intention but I don't see the value in terms of porting an entire codebase. The amount of additional functionality needed doesn't warrant a port.
